name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npx prettier --write .
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27